name: Dependabot Auto Merge

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve PR (patch/minor)
        if: contains('version-update:semver-patch,version-update:semver-minor', steps.metadata.outputs.update-type)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr review ${{ github.event.pull_request.number }} --approve

      - name: Enable auto-merge (squash)
        if: contains('version-update:semver-patch,version-update:semver-minor', steps.metadata.outputs.update-type)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge ${{ github.event.pull_request.number }} --auto --squash
